---
common_env_name: "{{ env_name | default('dev') }}"
common_base_dir: "{{ lookup('env', 'POCKET_LAB_BASE_DIR') | default('/data/data/com.termux/files/home/pocket-lab', true) }}"
common_iac_dir: "{{ common_base_dir }}/pocket_lab_iac"
common_api_dir: "{{ common_base_dir }}/api"
common_pwa_dir: "{{ common_base_dir }}/pwa_dist"
common_policies_dir: "{{ common_base_dir }}/pocket_lab_policies"
common_gitea_dir: "{{ common_base_dir }}/gitea"
common_runner_dir: "{{ common_base_dir }}/gitea-runners"
common_vault_dir: "{{ common_base_dir }}/vault"
common_observability_dir: "{{ common_base_dir }}/observability_configs"
common_backup_dir: "{{ common_base_dir }}/backups"
common_nats_dir: "{{ common_state_dir }}/nats"
common_log_dir: "{{ common_base_dir }}/logs"
common_run_dir: "{{ common_base_dir }}/run"
common_cache_dir: "{{ common_base_dir }}/cache"
common_state_dir: "{{ common_base_dir }}/state"
common_manage_dirs:
  - "{{ common_base_dir }}"
  - "{{ common_log_dir }}"
  - "{{ common_run_dir }}"
  - "{{ common_cache_dir }}"
  - "{{ common_state_dir }}"
  - "{{ common_iac_dir }}"
  - "{{ common_api_dir }}"
  - "{{ common_pwa_dir }}"
  - "{{ common_policies_dir }}"
  - "{{ common_gitea_dir }}"
  - "{{ common_gitea_dir }}/conf"
  - "{{ common_runner_dir }}"
  - "{{ common_vault_dir }}"
  - "{{ common_vault_dir }}/data"
  - "{{ common_vault_dir }}/audit"
  - "{{ common_backup_dir }}"
  - "{{ common_observability_dir }}"
  - "{{ common_nats_dir }}"
  - "{{ common_nats_dir }}/store"
