---
opa_version: "v0.62.1"
opa_arch: "linux_arm64_static"
opa_bin_dir: "/data/data/com.termux/files/usr/bin"
opa_policies_dir: "{{ common_policies_dir }}"
opa_interceptor_dest: "{{ common_api_dir }}/opa_interceptor.py"
